### ISSUE TITLE
need help, using mac mini m2 pro 

### ISSUE THREAD

**Issue by osmania101** [Winfredy/SadTalker#166]
dlib False
Installing requirements for SadTalker
Error executing callback ui_tabs_callback for /Users/london/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py
Traceback (most recent call last):
  File "/Users/london/stable-diffusion-webui/modules/script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "/Users/london/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 81, in on_ui_tabs
    install()
  File "/Users/london/stable-diffusion-webui/extensions/SadTalker/scripts/extension.py", line 54, in install
    launch.run_pip("install "+ v, "requirements for SadTalker")
  File "/Users/london/stable-diffusion-webui/launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/Users/london/stable-diffusion-webui/launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for SadTalker.
Command: "/Users/london/stable-diffusion-webui/venv/bin/python3.10" -m pip install dlib-bin --prefer-binary
Error code: 1
stdout: <empty>
stderr: ERROR: Could not find a version that satisfies the requirement dlib-bin (from versions: none)
ERROR: No matching distribution found for dlib-bin

I'm getting thise error codes , I followed the instructions

**Comment by vinthony** [comment]
similar to #163 , I will try to fix the usage of Macbook recently.

**Comment by vinthony** [comment]
fixed in https://github.com/Winfredy/SadTalker/commit/0c3649b88a14663cda779f81663b0694a118693b

**Comment by Semonxue** [comment]
I solve this after installed 
- `cmake`,`boost` and  `OpenCV` with brew.
-  `dlib` with brew

**Comment by vinthony** [comment]
We have fixed the installation of the Macbook, please try the latest code :)

**Comment by Semonxue** [comment]
> We have fixed the installation of the Macbook, please try the latest code :)

Yes, great work! I just tried the new version before the I posted . But the dependent files do not seem to be installed automatically, so I have to install manually. Now I don't have a clean mac to re-install it.

**Comment by vinthony** [comment]
> > We have fixed the installation of the Macbook, please try the latest code :)
> 
> Yes, great work! I just tried the new version before the I posted . But the dependent files do not seem to be installed automatically, so I have to install manually. Now I don't have a clean mac to re-install it.

Your experiment is also valuable, thanks for your sharing.

**Comment by IchvanHuang** [comment]
> We have fixed the installation of the Macbook, please try the latest code :)

Hi, I executed the latest code, but it seems I still encountered this same problem, my python version is 3.8.16. I have tried couple method but still have same errors reported
